dataset_name: OASIS_v1
img_size: [160, 224, 192]
transmorph_dir: /homebase/TransMorph_Transformer_for_Medical_Image_Registration/OASIS/TransMorph
voxelmorph_models_path: /homebase/LUMIR_L2R/VoxelMorph/models.py
train_dir: /database/OASIS/OASIS_official/oasis_organized/split_v1/train
val_dir: /database/OASIS/OASIS_official/oasis_organized/split_v1/val
test_dir: /database/OASIS/OASIS_official/oasis_organized/split_v1/test
json_path: /database/OASIS/OASIS_official/oasis_organized/split_v1/dataset.json
