# configs/config_oasis_v1.yaml

### Note:
#     1. vxm model
#            There is no official voxelmorph in the TransMorph/OASIS folder, I will use LUMIR_L2R for now
#     2. img_size
#            OASIS_v1 is reoriented to match with LUMIR in its dataloader:
#                /homebase/DL_projects/wavereg/scripts/250218_oasis_v1/myutils/datasets.py
dataset_name: L2R20Task3_AbdominalCT_v2
img_size: [192, 160, 256]
transmorph_dir: /homebase/DL_projects/wavereg/TransMorph_Transformer_for_Medical_Image_Registration/OASIS/TransMorph
voxelmorph_models_path: /homebase/DL_projects/wavereg/LUMIR_L2R/VoxelMorph/models.py
train_dir: /database/wavereg/datasets/L2R20Task3_AbdominalCT/split_v2 #/train # specified in json
val_dir: /database/wavereg/datasets/L2R20Task3_AbdominalCT/split_v2   #/val # specified in json
test_dir: /database/wavereg/datasets/L2R20Task3_AbdominalCT/split_v2   #/test # specified in json
json_path: /database/wavereg/datasets/L2R20Task3_AbdominalCT/split_v2/dataset.json
