dataset_name: L2R20Task3_AbdominalCT_v2
img_size: [192, 160, 256]
transmorph_dir: /homebase/TransMorph_Transformer_for_Medical_Image_Registration/OASIS/TransMorph
voxelmorph_models_path: /homebase/LUMIR_L2R/VoxelMorph/models.py
train_dir: /database/L2R20Task3_AbdominalCT/split_v2 #/train # specified in json
val_dir: /database/L2R20Task3_AbdominalCT/split_v2   #/val # specified in json
test_dir: /database/L2R20Task3_AbdominalCT/split_v2   #/test # specified in json
json_path: /database/L2R20Task3_AbdominalCT/split_v2/dataset.json
